<a href="https://colab.research.google.com/github/vsathyap/PyTorch_Fundamentals/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This jupyter notebook folllows the youtube tutorial: Deep Leaning with PyTorch (https://www.youtube.com/playlist?list=PLCC34OHNcOtpcgR9LEYSdi9r7XIbpkpK1)

#**Tutorial 1: Intro to Collab**

In [ ]:
# List the packages that exist
# To update this as necesary, check this out: https://docs.pytorch.org/tutorials/beginner/colab.html
!pip list

# **Tutorial 2: Intro to Tensors**

## LIST

In [6]:
my_list = [[1,2,3,4],[6,7,8,9]]
my_list

[[1, 2, 3, 4], [6, 7, 8, 9]]

## NUMPY ARRAYS

In [4]:
# import the numpy library
import numpy as np

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.93041314, 0.18688417, 0.20969364, 0.49603007],
       [0.14446732, 0.47229906, 0.40070484, 0.05655173],
       [0.56174163, 0.67462234, 0.01324081, 0.10059166]])

In [17]:
# To check the data type
# numpy arrays are by default float32
np1.dtype

dtype('float64')

## TENSORS

In [7]:
#import torch to use tensors
import torch

In [12]:
t1 = torch.randn(3,4)
t1

tensor([[-0.6201, -1.0895,  0.0208,  0.7880],
        [ 1.0025, -0.4710, -0.0817,  0.3952],
        [-0.4156,  0.5646,  0.7904,  0.7741]])

In [13]:
#Check the data type
# Tensors are by default float32
t1.dtype

torch.float32

In [16]:
# Creating a tensor from a numpy array
t2 = torch.tensor(np1)
t2

tensor([[0.9304, 0.1869, 0.2097, 0.4960],
        [0.1445, 0.4723, 0.4007, 0.0566],
        [0.5617, 0.6746, 0.0132, 0.1006]], dtype=torch.float64)

# **Tutorial 3: Tensor Operations**

In [18]:
import torch

In [20]:
# to create a tensor from 0->n-1 use arange(n)
t1  = torch.arange(10)
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 'RESHAPE' & 'VIEW'

In [22]:
# Using Reshape
t1 = t1.reshape(2,5)
t1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
# Reshape when we don't know the number of items
t2 = torch.arange(10)
print(f"t1 = {t1}")
t2 = t2.reshape(2,-1)
print(f"t2 = {t2}")
t2 = t2.reshape(-1,10)
print(f"t2 = {t2}")

t1 = tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
t2 = tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
t2 = tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [29]:
t3 = torch.arange(10)
t3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# Using View
t3 = t3.view(2,5)
t3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
# With reshape and view, the variables will update
t5 = torch.arange(10)
print(f"Original t5 = {t5}")
t6 = t5.reshape(5,-1)
print(f"Original t6 = {t6}")
t5[0] = 999
print(f"Modified t5 = {t5}")
print(f"Modified t6 = {t6}")

Original t5 = tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Original t6 = tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
Modified t5 = tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])
Modified t6 = tensor([[999,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])


In [35]:
# Grab a slice of a tensor
t7 = torch.arange(8)
print(f"t7 = {t7}")
t7 = t7.reshape(4,-1)
print(f"Reshaped t7 = {t7}")
print(f"t7[:,1] = {t7[:,1]}")
print(f"To retain the column shape use, t7[:,1:] = {t7[:,1:]}")


t7 = tensor([0, 1, 2, 3, 4, 5, 6, 7])
Reshaped t7 = tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
t7[:,1] = tensor([1, 3, 5, 7])
To retain the column shape use, t7[:,1:] = tensor([[1],
        [3],
        [5],
        [7]])


# **Tutorial 4: Tensor Math Operations**

In [36]:
import torch
import numpy as np

In [37]:
t_a = torch.tensor([1,2,3,4])
t_b = torch.tensor([5,6,7,8])


In [40]:
# Addition short-hand
t_a + t_b

tensor([ 6,  8, 10, 12])

In [39]:
#Addition long-hand (using functions)
torch.add(t_a,t_b)

tensor([ 6,  8, 10, 12])

In [41]:
# Subtraction
t_a - t_b

tensor([-4, -4, -4, -4])

In [45]:
#Subtraction long-hand (using functions)
torch.sub(t_a,t_b)

tensor([-4, -4, -4, -4])

In [42]:
#Multiplication
t_a*t_b

tensor([ 5, 12, 21, 32])

In [46]:
#Multiplication long-hand (using functions)
torch.mul(t_a,t_b)

tensor([ 5, 12, 21, 32])

In [43]:
# Division
t_a/t_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [47]:
#Division long-hand (using functions)
torch.div(t_a,t_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [44]:
#Remainder
t_a % t_b

tensor([1, 2, 3, 4])

In [48]:
#Remainder long-hand (using functions)
torch.remainder(t_a,t_b)

tensor([1, 2, 3, 4])

In [50]:
#Exponent
t_a**t_b

tensor([    1,    64,  2187, 65536])

In [49]:
#Exponential long-hand (using functions)
torch.pow(t_a,t_b)

tensor([    1,    64,  2187, 65536])

In [56]:
# Reassignment
t_a = t_a + t_b
t_a

tensor([26, 32, 38, 44])

In [58]:
t_a.add_(t_b)

tensor([31, 38, 45, 52])

In [59]:
t_a

tensor([31, 38, 45, 52])